"""empty message

Revision ID: 889fb306834c
Revises: ed9282ce8a0f
Create Date: 2025-04-29 14:55:52.334087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889fb306834c'
down_revision = 'ed9282ce8a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint('email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
